# Generated by Django 5.1.2 on 2024-10-14 07:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threaduser',
            name='followings',
        ),
        migrations.RemoveField(
            model_name='threaduser',
            name='follows',
        ),
        migrations.AddField(
            model_name='threaduser',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='follows', to=settings.AUTH_USER_MODEL),
        ),
    ]
